

yugabyte:
  datasource:
    driver-class-name: com.yugabyte.Driver
###    url: jdbc:postgresql://us-west-2.d6ef4d85-b2bb-462e-bc25-0e8bbf565d92.aws.ybdb.io:5433/yugabyte?ssl=true&sslmode=verify-full&sslrootcert=C:\devl\wfb\hackathon\petclinic-spring-data-yugabytedb\.postgresql\root.crt
#    url: jdbc:yugabytedb://us-west-2.d6ef4d85-b2bb-462e-bc25-0e8bbf565d92.aws.ybdb.io:5433/yugabyte
    load-balance: true
    username: user2
    password: user#2
###################
    db-name: hackathon
    host: us-west-2.d6ef4d85-b2bb-462e-bc25-0e8bbf565d92.aws.ybdb.io
    port: 5433
    ssl-mode: verify-full
    ssl-root-cert: C:/devl/wfb/hackathon/yugabyte/certs/root.crt
    connect-timeout: 30000
    socket-timeout: 30000
    login-timeout: 30000




yugabyte-local:
  datasource:
    driver-class-name: com.yugabyte.Driver
    ###    url: jdbc:postgresql://us-west-2.d6ef4d85-b2bb-462e-bc25-0e8bbf565d92.aws.ybdb.io:5433/yugabyte?ssl=true&sslmode=verify-full&sslrootcert=C:\devl\wfb\hackathon\petclinic-spring-data-yugabytedb\.postgresql\root.crt
    #    url: jdbc:yugabytedb://us-west-2.d6ef4d85-b2bb-462e-bc25-0e8bbf565d92.aws.ybdb.io:5433/yugabyte
    load-balance: false
    username: yugabyte
    password: yugabyte
    ###################
    db-name: yugabyte
    host: 192.168.0.108
    port: 5433
    ssl-mode: disable
    ssl-root-cert: C:/devl/wfb/hackathon/yugabyte/certs/root.crt
    connect-timeout: 30000
    socket-timeout: 30000
    login-timeout: 30000


management:
  endpoints:
    web:
      base-path: /manage
      exposure.include: "*"

# Logging
logging.level:
  com.zaxxer.hikari: TRACE
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.yugabyte: DEBUG
  org.springframework.jdbc.core.JdbcTemplate: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: TRACE
